### ISSUE TITLE
Opening Baubles Inventory Messes With Inventory

### ISSUE THREAD

**Issue by BloodshotPico** [zabi94/BringMeTheRings#1]
So basically when I opened the GUI for adding some more baubles to my new ring slots, it messes up with the inventory and makes the items go everywhere but the extra ring slots don't get messed up at all.

Before:
![image](https://user-images.githubusercontent.com/5675428/55517827-ac131f80-5669-11e9-9106-b49166712161.png)

After:
![image](https://user-images.githubusercontent.com/5675428/55517842-b6351e00-5669-11e9-83f0-b6341d740778.png)

I do have to say that I've tested this on both Client and Server side and it only seems to mess up on the server side for some reason, there are no problems in singleplayer.

**Some details:**
Minecraft 1.12.2
Forge 14.23.5.2823
Baubles 1.12-1.5.2

**Comment by zabi94** [comment]
Why was this closed?

**Comment by BloodshotPico** [comment]
I remember it being something on my side sorry. Can't think back to what it was though, I think another mod was interfering with it.
