### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by shoverno2** [zabi94/BringMeTheRings#3]
When applying more then 24 slots for rings in confing Minecraft crashing.

**Comment by zabi94** [comment]
This tells me absolutely nothing.
When reporting a crash please post forge version, mod list with versions, crash log, and whether you were changing the config of a client or a server

**Comment by shoverno2** [comment]
Ok, any other information i will tell tomorrow. I'm going to sleep)
And then, tomorrow i will try 36 slots at new modpack with only 3 mods(one is yours, second is vanilla fix, and last is useful for interface size)

**Comment by shoverno2** [comment]
I don't know, but now there no any crash. Maybe one mod from mine modpack conflict with that.
