### ISSUE TITLE
Just wanna know how to config more slots in

### ISSUE THREAD

**Issue by VoxNiphili** [zabi94/BringMeTheRings#6]
This mod's a lifesaver, i can't get enough bauble slots. Just dunno how to ADD more, how to config it. Is there a command?

**Comment by zabi94** [comment]
There should be a file in your config folder, called bringmetgerings.cfg.
Just change the number inside and restart the game.

Make sure to set the same number on the server and every other client if you play multiplayer

**Comment by VoxNiphili** [comment]
ah, thanks.

**Comment by zabi94** [comment]
No problem!
